name: Docs CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "docs/**.md"
      - "docs/**/*.md"
      - "scripts/validate_docs.py"
      - ".github/workflows/docs-ci.yml"

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Validate docs front-matter
        run: |
          python3 scripts/validate_docs.py
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Lint Markdown
        run: npx markdownlint-cli2
